Added Prediction API but with issue
wiktorrudzki/Fuel-deliever-support-app pull request #20
Opened 2024-06-15 16:35 UTC by TomChuck10

Dodałem API dla Predcition i użyłem hooka useParams do rozdzielenia wartości po id dla konkretnych stacji ale wystąpił błąd związany z typem undefined. Próbowałem zmieniać kod na różne sposoby i korzystałem z chatu do pomocy ale nie pomogło.

2024-06-16 08:03 UTC, wiktorrudzki requested changes

2024-06-16 08:03 UTC, wiktorrudzki commented on client/src/views/Panel.tsx
> +  const [predictions, setPredictions] = useState<unknown[]>([]);
typ unknown, to nie jest dobra praktyka. Sprawdź co przyjdzie ci z backendu i utwórz stosowny typ

2024-06-16 08:03 UTC, wiktorrudzki commented on client/src/views/Panel.tsx
> +  const [getPrediction] = usePromise(getAllPredictions, (response) => {
skoro pobierasz wszystkie to nie `getPrediction` tylko `getPrediction`

2024-06-16 08:03 UTC, wiktorrudzki commented on client/src/views/Panel.tsx
> +  const { id } = useParams<{ id: string }>();
musisz najpierw zweryfikować, czy id istnieje. Typescript id ma za `string | undefined`, a nie za `string` tak jak ty uważasz

2024-06-17 16:47 UTC, TomChuck10 commented
![image](https://github.com/wiktorrudzki/Fuel-deliever-support-app/assets/115744357/e23ffeaf-375d-47ed-aced-88f4bcfe3e75)
![image](https://github.com/wiktorrudzki/Fuel-deliever-support-app/assets/115744357/1667935b-3144-43f1-949b-8bb7efaeab5d)

2024-06-17 16:53 UTC, wiktorrudzki commented on client/src/views/Panel.tsx
> +  const [predictions, setPredictions] = useState<Prediction | null>(null);
predictions -> prediction

2024-06-17 17:52 UTC, merged